name: Sync 'preview' with 'main'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-branches:
    name: Update 'preview' branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main' branch
        uses: actions/checkout@master

      - name: Checkout 'preview' branch
        uses: actions/checkout@master
        with:
          ref: preview

      - name: Sync 'preview' with 'main'
        run:
          git merge origin/main