name: Sync 'preview' with 'main'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-branches:
    name: Update 'preview' branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main' branch
        uses: actions/checkout@v2

      - name: Remove config file
        run:
          rm -f no-changes.txt

      - name: Checkout 'preview' branch
        uses: actions/checkout@v2
        with:
          ref: preview

      - name: Merge changes
        run:
          git config --global user.name "Your Name"
          git merge --allow-unrelated-histories origin/main