name: Sync 'preview' with 'main'

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  sync-branches:
    name: Update 'preview' branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main' branch
        uses: actions/checkout@master

      - name: Checkout 'preview' branch
        uses: actions/checkout@master
        with:
          ref: preview

      - name: Sync 'preview' with 'main'
        run: |
          git config user.name $GITHUB_ACTOR
          git config merge.theirs.driver true
          git config merge.ours.driver true
          git merge origin/main --allow-unrelated-histories
          git push origin/preview