name: Sync 'preview' with 'main'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-branches:
    name: Update 'preview' branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 'main' branch
        uses: actions/checkout@v2

      - name: Remove config file
        run:
          rm -f no-changes.txt

      - name: Merge main -> preview
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: preview
          github_token: ${{ secrets.GITHUB_TOKEN }}