name: Sync 'preview' with 'main'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-branches:
    name: Update 'preview' branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          ref: preview

      - name: Merge branches
        run:
          git merge origin/main